### ISSUE TITLE
Trucks being destroyed before getting to them.

### ISSUE THREAD

**Issue by Triga307** [Omega248/qb-banktruck#2]
**Expected Behavior**
The trucks do not get destroyed before getting to rob them.

**Current Behavior**
The problem is if anyone other then the person that started it is within a certain distance of the truck before the person that started it then it kills it. So with low population late at night I can get it to work 100% of the time by having all 3 of us stay away from it but if I have someone else drive towards it while I stand around it will kill it. If we all stay away from it then it just keeps driving until 1 of us gets near

**Possible Solution**
Not sure.

**Steps to Reproduce**
Do the jobs with over 10 people in the server.
**Detailed Description**

**Comment by Omega248** [comment]
I have fixed the bug but the script is not compatible with onesync, there will be desync issues if used on a server with onesync enabled (Pretty much every server) with the peds not being visible to everyone, peds losing tasks and the blips being lost after migrating to a closer client.
