### ISSUE TITLE
Cant rob the truck once guards are killed

### ISSUE THREAD

**Issue by InfamousRL** [Omega248/qb-banktruck#3]
**Expected Behavior**
Being able too use G too plant explosives and take the money

**Current Behavior**
Once killing the guards and taking the driver out if he dident fall out, you get too the back doors and theres no option too plate the bomb when it was there when you dident touch the driver, but if you leave the driver then the truck isnt empty.

**Possible Solution**
I have no clue as i feel its possible just using an older QB version so maybe an update of code would be needed.

**Steps to Reproduce**
Use latest QB artifact and game vbersion on 2545 

**Detailed Description**
stated in the current behavior as everything else works perfect did have too remove the spawnped and just make the ped spawn with target as target doesnt accept spawnped command but that was a easy fix

**Comment by Omega248** [comment]
If your job was set to police it makes it so you can't rob the truck, I have changed it so if your job is police you can still rob the truck 
https://github.com/Omega248/qb-banktruck/commit/ac97980843f889f7c7a2b37803ca49d08d13dbc2

The script is also not compatible with onesync so there will be general sync issues and migration issues.   
I have updated the readme to reflect this.
