### ISSUE TITLE
not able to rob van 

### ISSUE THREAD

**Issue by juppjup01** [Omega248/qb-banktruck#4]
**Expected Behavior**
to be able to rob the truck 

**Current Behavior**
Unable to use g to plant the c4, am given the code below 
**Possible Solution**
not sure? could i possibly have old version of the script where cops can't do it?

**Steps to Reproduce
the same thing happens every time
**Detailed Description**

script works fine until you take out the guards then give the errors as shown in the pic, am not really too sure what to do 

![banktruck error](https://user-images.githubusercontent.com/105734237/170780180-ec964e95-cda4-4cec-854e-138df869b621.png)

**Comment by GhostV-Survival** [comment]
Dispatch on the wrong row.
Remove the export from qb-dispatch.

And rename the script to original

**Comment by Omega248** [comment]
https://github.com/Omega248/qb-banktruck/commit/b14e2fa651fc4b5420a0ca218bf6d96816e77727 I added an easy to to change the dispatch script you are using and also completely disable if you are not using ps-dispatch or qb-dispatch.

**Comment by juppjup01** [comment]
okay well re downloaed, same error, i don't even have qb-dispatch, are you testing this or? because i'm pretty stumped and have spent hours messing around

**Comment by juppjup01** [comment]
wait sorry i think i just got it
