### ISSUE TITLE
Omega248 qb-banktruck /// NPC ped model doesn't spawn. (Please help)

### ISSUE THREAD

**Issue by Relay117** [Omega248/qb-banktruck#7]
**Expected Behavior**
Ped spawns, talk to the ped with qb-target

**Current Behavior**
Ped doesnt spawn, get this error.
(https://user-images.githubusercontent.com/110699813/183220676-cdb4396b-b01f-47db-8954-b84ae455147a.png)

**Possible Solution**
Dont know.

**Steps to Reproduce**
Did exactly as the read-me told me to do. Put the files in resources.

**Detailed Description**
When server starts i get the error on the screenshot, I dont know what I'm supposed to do with it. Maybe you can help?

**Comment by Omega248** [comment]
When did you last update qb-target?

**Comment by Relay117** [comment]
Not in a long time, every other script works fine. You think it is an old
version error?

lördag 6 augusti 2022 skrev Omega ***@***.***>:

**Comment by Relay117** [comment]
Do you have a link for the one you are using?

**Comment by Relay117** [comment]
I just downloaded the latest version still the same error.

**Comment by Omega248** [comment]
in your qb-target/client.lua at line 765 - 897 do you have this block of code

```
 local function SpawnPed(data)
	local spawnedped
	local key, value = next(data)
	if type(value) == 'table' and type(key) ~= 'string' then
		for _, v in pairs(data) do
			if v.spawnNow then
				RequestModel(v.model)
				while not HasModelLoaded(v.model) do
					Wait(0)
				end

				if type(v.model) == 'string' then v.model = joaat(v.model) end

				if v.minusOne then
					spawnedped = CreatePed(0, v.model, v.coords.x, v.coords.y, v.coords.z - 1.0, v.coords.w or 0.0, >v.networked or false, true)
				else
					spawnedped = CreatePed(0, v.model, v.coords.x, v.coords.y, v.coords.z, v.coords.w or 0.0, v.networked >or false, true)
				end

				if v.freeze then
					FreezeEntityPosition(spawnedped, true)
				end

				if v.invincible then
					SetEntityInvincible(spawnedped, true)
				end

				if v.blockevents then
					SetBlockingOfNonTemporaryEvents(spawnedped, true)
				end

				if v.animDict and v.anim then
					RequestAnimDict(v.animDict)
					while not HasAnimDictLoaded(v.animDict) do
						Wait(0)
					end

					TaskPlayAnim(spawnedped, v.animDict, v.anim, 8.0, 0, -1, v.flag or 1, 0, 0, 0, 0)
				end

				if v.scenario then
					SetPedCanPlayAmbientAnims(spawnedped, true)
					TaskStartScenarioInPlace(spawnedped, v.scenario, 0, true)
				end

				if v.target then
					if v.target.useModel then
						AddTargetModel(v.model, {
							options = v.target.options,
							distance = v.target.distance
						})
					else
						AddTargetEntity(spawnedped, {
							options = v.target.options,
							distance = v.target.distance
						})
					end
				end

				v.currentpednumber = spawnedped
			end

			local nextnumber = #Config.Peds + 1
			if nextnumber <= 0 then nextnumber = 1 end

			Config.Peds[nextnumber] = v
		end
	else
		if data.spawnNow then
			RequestModel(data.model)
			while not HasModelLoaded(data.model) do
				Wait(0)
			end

			if type(data.model) == 'string' then data.model = joaat(data.model) end

			if data.minusOne then
				spawnedped = CreatePed(0, data.model, data.coords.x, data.coords.y, data.coords.z - 1.0, data.coords.w, >data.networked or false, true)
			else
				spawnedped = CreatePed(0, data.model, data.coords.x, data.coords.y, data.coords.z, data.coords.w, >data.networked or false, true)
			end

			if data.freeze then
				FreezeEntityPosition(spawnedped, true)
			end

			if data.invincible then
				SetEntityInvincible(spawnedped, true)
			end

			if data.blockevents then
				SetBlockingOfNonTemporaryEvents(spawnedped, true)
			end

			if data.animDict and data.anim then
				RequestAnimDict(data.animDict)
				while not HasAnimDictLoaded(data.animDict) do
					Wait(0)
				end

				TaskPlayAnim(spawnedped, data.animDict, data.anim, 8.0, 0, -1, data.flag or 1, 0, 0, 0, 0)
			end

			if data.scenario then
				SetPedCanPlayAmbientAnims(spawnedped, true)
				TaskStartScenarioInPlace(spawnedped, data.scenario, 0, true)
			end

			if data.target then
				if data.target.useModel then
					AddTargetModel(data.model, {
						options = data.target.options,
						distance = data.target.distance
					})
				else
					AddTargetEntity(spawnedped, {
						options = data.target.options,
						distance = data.target.distance
					})
				end
			end

			data.currentpednumber = spawnedped
		end

		local nextnumber = #Config.Peds + 1
		if nextnumber <= 0 then nextnumber = 1 end

		Config.Peds[nextnumber] = data
	end
end

exports("SpawnPed", SpawnPed)
```

**Comment by Relay117** [comment]
Yes I do, everything is exactly like that. Still doesn't work.

**Comment by Omega248** [comment]
I would try deleting qb-target and qb-banktruck and reinstalling them both and make sure you start qb-target before qb-banktruck.

**Comment by Relay117** [comment]
Ok thanks, we get the same error on other scripts as well that depend on peds. So im gonna try that!

**Comment by Omega248** [comment]
No problem, I'm pretty sure the problem spans from starting other scripts that rely on qb-target before qb-target

**Comment by Relay117** [comment]
Okay, this is how our script starting system works, where we ensure scripts:

# Voice config
setr voice_useNativeAudio true
setr voice_useSendingRangeOnly true
setr voice_defaultCycle "GRAVE"
setr voice_defaultVolume 0.3
setr voice_enableRadioAnim 1
setr voice_syncData 1

# QBCore locale config
setr qb_locale "en"

# QBCore UseTarget
setr UseTarget false

# These resources will start by default.
ensure mapmanager
ensure chat
ensure spawnmanager
ensure sessionmanager
ensure basic-gamemode
ensure hardcap
ensure baseevents


sv_enforceGameBuild 2612

# QBCore & Extra stuff
ensure qb-target
ensure qb-core
ensure [qb]
ensure [standalone]
ensure [voice]
ensure [defaultmaps]
ensure [maps]
ensure [vehicles]
ensure [assets]
ensure [loading screen]

**Comment by Omega248** [comment]
ensure qb-target after qb-core

**Comment by Relay117** [comment]
ok thank you will try!

**Comment by Relay117** [comment]
Ok, thankfully the ped works now and i get so far as blowing up the back doors, when this error appears:

(https://user-images.githubusercontent.com/110699813/183269763-251b58d2-c2c6-4060-b40f-f3318465ed0c.png)

**Comment by Omega248** [comment]
In the config you need to set it to false if you are not using qb-dispatch or ps-dispatch if you are using ps-dispatch instead of qb-dispatch change it to ps-dispatch

![image](https://user-images.githubusercontent.com/86800507/183276375-4325e95c-757f-4728-913c-7497ce9d0604.png)

**Comment by Relay117** [comment]
thanks!
It works now
